export const EDIT_PROFILE = "EDIT_PROFILE"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const RESET_PROFILE_FLAG = "RESET_PROFILE_FLAG";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const API_CALL_SUCCESS = "API_CALL_SUCCESS"
export const API_CALL_FAILURE = "API_CALL_FAILURE"