// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_ALL_PROJECTS_DATA = "GET_ALL_PROJECTS_DATA";
export const DEL_A_PROJECT = "DEL_A_PROJECT"
export const API_DEL_PROJECT = "API_DEL_PROJECT"
export const DEACTIVATE_TOUR = "DEACTIVATE_TOUR"
export const GET_USER_TOURS = "GET_USER_TOURS"
