export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESSFUL = "REGISTER_USER_SUCCESSFUL"
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED"
export const RESET_REGISTER_FLAG = "RESET_REGISTER_FLAG";
export const REQUEST_USER_ACTIVATION = "REQUEST_USER_ACTIVATION";
export const REQUEST_USER_REACTIVATION = "REQUEST_USER_REACTIVATION";
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS"
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR"