export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const API_SUCCESS_RESET_PASS = "API_SUCCESS_RESET_PASS"
export const API_ERROR_RESET_PASS = "API_ERROR_RESET_PASS"
export const RESET_PASSWORD = "RESET_PASSWORD"
